// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagementSystem.Api;

#nullable disable

namespace TaskManagementSystem.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250816185849_SeedTask")]
    partial class SeedTask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagementSystem.Api.Entities.ToDoTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Complete the final draft of the project report and send it to the manager.",
                            DueDate = new DateTime(2025, 8, 19, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Finish project report"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Buy vegetables, fruits, and milk for the week.",
                            DueDate = new DateTime(2025, 8, 17, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Grocery shopping"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Routine dental check-up at the downtown clinic.",
                            DueDate = new DateTime(2025, 8, 23, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Dentist appointment"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Pay the monthly electricity bill before the due date.",
                            DueDate = new DateTime(2025, 8, 14, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            Title = "Pay electricity bill"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Weekly sync-up meeting with the development team.",
                            DueDate = new DateTime(2025, 8, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Team meeting"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
